
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("c1472d2e-22c0-43dc-8bec-65eeef32c26c")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MainModel", "FK_SideBarRole_SideBarMenu", "SideBarMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SideBarMenu), "SideBarRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SideBarRole), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MainEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MainEntities object using the connection string found in the 'MainEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MainEntities", "MainEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MainEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MainEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MainEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MainEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SideBarMenus() As ObjectSet(Of SideBarMenu)
        Get
            If (_SideBarMenus Is Nothing) Then
                _SideBarMenus = MyBase.CreateObjectSet(Of SideBarMenu)("SideBarMenus")
            End If
            Return _SideBarMenus
        End Get
    End Property

    Private _SideBarMenus As ObjectSet(Of SideBarMenu)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SideBarRoles() As ObjectSet(Of SideBarRole)
        Get
            If (_SideBarRoles Is Nothing) Then
                _SideBarRoles = MyBase.CreateObjectSet(Of SideBarRole)("SideBarRoles")
            End If
            Return _SideBarRoles
        End Get
    End Property

    Private _SideBarRoles As ObjectSet(Of SideBarRole)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SideBarMenus EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSideBarMenus(ByVal sideBarMenu As SideBarMenu)
        MyBase.AddObject("SideBarMenus", sideBarMenu)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SideBarRoles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSideBarRoles(ByVal sideBarRole As SideBarRole)
        MyBase.AddObject("SideBarRoles", sideBarRole)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MainModel", Name:="SideBarMenu")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SideBarMenu
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SideBarMenu object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="parentId">Initial value of the ParentId property.</param>
    ''' <param name="actionLink">Initial value of the ActionLink property.</param>
    ''' <param name="label">Initial value of the Label property.</param>
    ''' <param name="icon">Initial value of the Icon property.</param>
    ''' <param name="ordinal">Initial value of the Ordinal property.</param>
    ''' <param name="module">Initial value of the Module property.</param>
    Public Shared Function CreateSideBarMenu(id As Global.System.Int32, parentId As Global.System.Int32, actionLink As Global.System.String, label As Global.System.String, icon As Global.System.String, ordinal As Global.System.Int32, [module] As Global.System.String) As SideBarMenu
        Dim sideBarMenu as SideBarMenu = New SideBarMenu
        sideBarMenu.ID = id
        sideBarMenu.ParentId = parentId
        sideBarMenu.ActionLink = actionLink
        sideBarMenu.Label = label
        sideBarMenu.Icon = icon
        sideBarMenu.Ordinal = ordinal
        sideBarMenu.[Module] = [module]
        Return sideBarMenu
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParentId() As Global.System.Int32
        Get
            Return _ParentId
        End Get
        Set
            OnParentIdChanging(value)
            ReportPropertyChanging("ParentId")
            _ParentId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ParentId")
            OnParentIdChanged()
        End Set
    End Property

    Private _ParentId As Global.System.Int32
    Private Partial Sub OnParentIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnParentIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ActionLink() As Global.System.String
        Get
            Return _ActionLink
        End Get
        Set
            OnActionLinkChanging(value)
            ReportPropertyChanging("ActionLink")
            _ActionLink = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ActionLink")
            OnActionLinkChanged()
        End Set
    End Property

    Private _ActionLink As Global.System.String
    Private Partial Sub OnActionLinkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnActionLinkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Label() As Global.System.String
        Get
            Return _Label
        End Get
        Set
            OnLabelChanging(value)
            ReportPropertyChanging("Label")
            _Label = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Label")
            OnLabelChanged()
        End Set
    End Property

    Private _Label As Global.System.String
    Private Partial Sub OnLabelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLabelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Icon() As Global.System.String
        Get
            Return _Icon
        End Get
        Set
            OnIconChanging(value)
            ReportPropertyChanging("Icon")
            _Icon = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Icon")
            OnIconChanged()
        End Set
    End Property

    Private _Icon As Global.System.String
    Private Partial Sub OnIconChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIconChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ordinal() As Global.System.Int32
        Get
            Return _Ordinal
        End Get
        Set
            OnOrdinalChanging(value)
            ReportPropertyChanging("Ordinal")
            _Ordinal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Ordinal")
            OnOrdinalChanged()
        End Set
    End Property

    Private _Ordinal As Global.System.Int32
    Private Partial Sub OnOrdinalChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOrdinalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Module]() As Global.System.String
        Get
            Return _Module
        End Get
        Set
            OnModuleChanging(value)
            ReportPropertyChanging("Module")
            _Module = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Module")
            OnModuleChanged()
        End Set
    End Property

    Private _Module As Global.System.String
    Private Partial Sub OnModuleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModuleChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MainModel", "FK_SideBarRole_SideBarMenu", "SideBarRole")>
     Public Property SideBarRoles() As EntityCollection(Of SideBarRole)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SideBarRole)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SideBarRole)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarRole", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MainModel", Name:="SideBarRole")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SideBarRole
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SideBarRole object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="sideBarMenuId">Initial value of the SideBarMenuId property.</param>
    ''' <param name="roleName">Initial value of the RoleName property.</param>
    Public Shared Function CreateSideBarRole(id As Global.System.Int32, sideBarMenuId As Global.System.Int32, roleName As Global.System.String) As SideBarRole
        Dim sideBarRole as SideBarRole = New SideBarRole
        sideBarRole.ID = id
        sideBarRole.SideBarMenuId = sideBarMenuId
        sideBarRole.RoleName = roleName
        Return sideBarRole
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SideBarMenuId() As Global.System.Int32
        Get
            Return _SideBarMenuId
        End Get
        Set
            OnSideBarMenuIdChanging(value)
            ReportPropertyChanging("SideBarMenuId")
            _SideBarMenuId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SideBarMenuId")
            OnSideBarMenuIdChanged()
        End Set
    End Property

    Private _SideBarMenuId As Global.System.Int32
    Private Partial Sub OnSideBarMenuIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSideBarMenuIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RoleName() As Global.System.String
        Get
            Return _RoleName
        End Get
        Set
            OnRoleNameChanging(value)
            ReportPropertyChanging("RoleName")
            _RoleName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RoleName")
            OnRoleNameChanged()
        End Set
    End Property

    Private _RoleName As Global.System.String
    Private Partial Sub OnRoleNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRoleNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MainModel", "FK_SideBarRole_SideBarMenu", "SideBarMenu")>
    Public Property SideBarMenu() As SideBarMenu
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SideBarMenu)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarMenu").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SideBarMenu)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarMenu").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SideBarMenuReference() As EntityReference(Of SideBarMenu)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SideBarMenu)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarMenu")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SideBarMenu)("MainModel.FK_SideBarRole_SideBarMenu", "SideBarMenu", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


