Public Class ModelDetailHeavyEqpActivities
    Public Property Activity As Integer
    Public Property Code As String
    Public Property Merk As String
    Public Property Type As String
    Public Property [Operator] As String
    Public Property IDOp As Integer
    Public Property [Date] As Date
    Public Property Day As String
    Public Property BeginSecondOverTime As TimeSpan
    Public Property EndSecondOverTime As TimeSpan
    Public Property BeginNormalI As TimeSpan
    Public Property EndNormalI As TimeSpan
    Public Property BeginBreakI As TimeSpan
    Public Property EndBreakI As TimeSpan
    Public Property BeginNormalII As TimeSpan
    Public Property EndNormalII As TimeSpan
    Public Property BeginBreakII As TimeSpan
    Public Property EndBreakII As TimeSpan
    Public Property BeginFirstOverTime1 As TimeSpan
    Public Property EndFirstOverTime1 As TimeSpan
    Public Property BeginFirstOverTime2 As TimeSpan
    Public Property EndFirstOverTime2 As TimeSpan
    Public Property IDOperation As Integer
    Public Property IDOpActivity As Integer
    Public Property OperationType As String
    Public Property VolumeOperation As Decimal
    Public Property LocationOperation As String
    Public Property BeginHM As Decimal
    Public Property EndHM As Decimal
    Public Property PacketOperation As String
    Public Property IDNonOperation As Integer
    Public Property IDNonOpActivity As Integer
    Public Property Begin As TimeSpan
    Public Property [End] As TimeSpan
    Public Property Reason As String
    Public Property IDOil As Integer
    Public Property IDOilActivity As Integer
    Public Property OilType As String
    Public Property Amount As Integer
    Public Property IDFuel As Integer
    Public Property IDFuelActivity As Integer
    Public Property AmountFuel As Integer
End Class
