
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("ccf061ab-70d3-4e42-8f7c-e6dbdb6c981a")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("HRDModel", "FK_Master_Personal_Occupation", "Occupation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Occupation), "Master_Personal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Master_Personal), True)>
<Assembly: EdmRelationshipAttribute("HRDModel", "FK_Occupation_ManagementLevel", "ManagementLevel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ManagementLevel), "Occupation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Occupation), True)>
<Assembly: EdmRelationshipAttribute("HRDModel", "vOfficeMaster_Personal", "vOffice", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(vOffice), "Master_Personal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Master_Personal), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class HrdEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new HrdEntities object using the connection string found in the 'HrdEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=HrdEntities", "HrdEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new HrdEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "HrdEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new HrdEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "HrdEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Master_Personal() As ObjectSet(Of Master_Personal)
        Get
            If (_Master_Personal Is Nothing) Then
                _Master_Personal = MyBase.CreateObjectSet(Of Master_Personal)("Master_Personal")
            End If
            Return _Master_Personal
        End Get
    End Property

    Private _Master_Personal As ObjectSet(Of Master_Personal)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Occupations() As ObjectSet(Of Occupation)
        Get
            If (_Occupations Is Nothing) Then
                _Occupations = MyBase.CreateObjectSet(Of Occupation)("Occupations")
            End If
            Return _Occupations
        End Get
    End Property

    Private _Occupations As ObjectSet(Of Occupation)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ManagementLevels() As ObjectSet(Of ManagementLevel)
        Get
            If (_ManagementLevels Is Nothing) Then
                _ManagementLevels = MyBase.CreateObjectSet(Of ManagementLevel)("ManagementLevels")
            End If
            Return _ManagementLevels
        End Get
    End Property

    Private _ManagementLevels As ObjectSet(Of ManagementLevel)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property vOffices() As ObjectSet(Of vOffice)
        Get
            If (_vOffices Is Nothing) Then
                _vOffices = MyBase.CreateObjectSet(Of vOffice)("vOffices")
            End If
            Return _vOffices
        End Get
    End Property

    Private _vOffices As ObjectSet(Of vOffice)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property EmployeeOvertimes() As ObjectSet(Of EmployeeOvertime)
        Get
            If (_EmployeeOvertimes Is Nothing) Then
                _EmployeeOvertimes = MyBase.CreateObjectSet(Of EmployeeOvertime)("EmployeeOvertimes")
            End If
            Return _EmployeeOvertimes
        End Get
    End Property

    Private _EmployeeOvertimes As ObjectSet(Of EmployeeOvertime)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Master_Personal EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMaster_Personal(ByVal master_Personal As Master_Personal)
        MyBase.AddObject("Master_Personal", master_Personal)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Occupations EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOccupations(ByVal occupation As Occupation)
        MyBase.AddObject("Occupations", occupation)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ManagementLevels EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToManagementLevels(ByVal managementLevel As ManagementLevel)
        MyBase.AddObject("ManagementLevels", managementLevel)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the vOffices EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTovOffices(ByVal vOffice As vOffice)
        MyBase.AddObject("vOffices", vOffice)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the EmployeeOvertimes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToEmployeeOvertimes(ByVal employeeOvertime As EmployeeOvertime)
        MyBase.AddObject("EmployeeOvertimes", employeeOvertime)
    End Sub

    #End Region

    #Region "Function Imports"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    ''' <param name="id">No Metadata Documentation available.</param>
    Public Function ReportEmployee(id As Nullable(Of Global.System.Int32)) As ObjectResult(Of ReportEmployee_Result)
        Dim idParameter As ObjectParameter
        If (id.HasValue)
            idParameter = New ObjectParameter("id", id)
        Else
            idParameter = New ObjectParameter("id", GetType(Global.System.Int32))
        End If

        Return MyBase.ExecuteFunction(Of ReportEmployee_Result)("ReportEmployee", idParameter)

    End Function

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HRDModel", Name:="EmployeeOvertime")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class EmployeeOvertime
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new EmployeeOvertime object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="employeeId">Initial value of the EmployeeId property.</param>
    ''' <param name="activity">Initial value of the Activity property.</param>
    ''' <param name="activityDate">Initial value of the ActivityDate property.</param>
    ''' <param name="officeId">Initial value of the OfficeId property.</param>
    Public Shared Function CreateEmployeeOvertime(id As Global.System.Int32, employeeId As Global.System.Int32, activity As Global.System.String, activityDate As Global.System.DateTime, officeId As Global.System.Int32) As EmployeeOvertime
        Dim employeeOvertime as EmployeeOvertime = New EmployeeOvertime
        employeeOvertime.Id = id
        employeeOvertime.EmployeeId = employeeId
        employeeOvertime.Activity = activity
        employeeOvertime.ActivityDate = activityDate
        employeeOvertime.OfficeId = officeId
        Return employeeOvertime
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EmployeeId() As Global.System.Int32
        Get
            Return _EmployeeId
        End Get
        Set
            OnEmployeeIdChanging(value)
            ReportPropertyChanging("EmployeeId")
            _EmployeeId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EmployeeId")
            OnEmployeeIdChanged()
        End Set
    End Property

    Private _EmployeeId As Global.System.Int32
    Private Partial Sub OnEmployeeIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnEmployeeIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Activity() As Global.System.String
        Get
            Return _Activity
        End Get
        Set
            OnActivityChanging(value)
            ReportPropertyChanging("Activity")
            _Activity = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Activity")
            OnActivityChanged()
        End Set
    End Property

    Private _Activity As Global.System.String
    Private Partial Sub OnActivityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnActivityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BeginOvertime1Morning() As Nullable(Of Global.System.DateTime)
        Get
            Return _BeginOvertime1Morning
        End Get
        Set
            OnBeginOvertime1MorningChanging(value)
            ReportPropertyChanging("BeginOvertime1Morning")
            _BeginOvertime1Morning = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BeginOvertime1Morning")
            OnBeginOvertime1MorningChanged()
        End Set
    End Property

    Private _BeginOvertime1Morning As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnBeginOvertime1MorningChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnBeginOvertime1MorningChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndOvertime1Morning() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndOvertime1Morning
        End Get
        Set
            OnEndOvertime1MorningChanging(value)
            ReportPropertyChanging("EndOvertime1Morning")
            _EndOvertime1Morning = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndOvertime1Morning")
            OnEndOvertime1MorningChanged()
        End Set
    End Property

    Private _EndOvertime1Morning As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndOvertime1MorningChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndOvertime1MorningChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BeginOvertime1Afternoon() As Nullable(Of Global.System.DateTime)
        Get
            Return _BeginOvertime1Afternoon
        End Get
        Set
            OnBeginOvertime1AfternoonChanging(value)
            ReportPropertyChanging("BeginOvertime1Afternoon")
            _BeginOvertime1Afternoon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BeginOvertime1Afternoon")
            OnBeginOvertime1AfternoonChanged()
        End Set
    End Property

    Private _BeginOvertime1Afternoon As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnBeginOvertime1AfternoonChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnBeginOvertime1AfternoonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndOvertime1Afternoon() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndOvertime1Afternoon
        End Get
        Set
            OnEndOvertime1AfternoonChanging(value)
            ReportPropertyChanging("EndOvertime1Afternoon")
            _EndOvertime1Afternoon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndOvertime1Afternoon")
            OnEndOvertime1AfternoonChanged()
        End Set
    End Property

    Private _EndOvertime1Afternoon As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndOvertime1AfternoonChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndOvertime1AfternoonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BeginOvertime2() As Nullable(Of Global.System.DateTime)
        Get
            Return _BeginOvertime2
        End Get
        Set
            OnBeginOvertime2Changing(value)
            ReportPropertyChanging("BeginOvertime2")
            _BeginOvertime2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BeginOvertime2")
            OnBeginOvertime2Changed()
        End Set
    End Property

    Private _BeginOvertime2 As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnBeginOvertime2Changing(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnBeginOvertime2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndOvertime2() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndOvertime2
        End Get
        Set
            OnEndOvertime2Changing(value)
            ReportPropertyChanging("EndOvertime2")
            _EndOvertime2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndOvertime2")
            OnEndOvertime2Changed()
        End Set
    End Property

    Private _EndOvertime2 As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndOvertime2Changing(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndOvertime2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ActivityDate() As Global.System.DateTime
        Get
            Return _ActivityDate
        End Get
        Set
            OnActivityDateChanging(value)
            ReportPropertyChanging("ActivityDate")
            _ActivityDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ActivityDate")
            OnActivityDateChanged()
        End Set
    End Property

    Private _ActivityDate As Global.System.DateTime
    Private Partial Sub OnActivityDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnActivityDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OfficeId() As Global.System.Int32
        Get
            Return _OfficeId
        End Get
        Set
            OnOfficeIdChanging(value)
            ReportPropertyChanging("OfficeId")
            _OfficeId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OfficeId")
            OnOfficeIdChanged()
        End Set
    End Property

    Private _OfficeId As Global.System.Int32
    Private Partial Sub OnOfficeIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOfficeIdChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HRDModel", Name:="ManagementLevel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ManagementLevel
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ManagementLevel object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="levelName">Initial value of the LevelName property.</param>
    Public Shared Function CreateManagementLevel(id As Global.System.Int32, levelName As Global.System.String) As ManagementLevel
        Dim managementLevel as ManagementLevel = New ManagementLevel
        managementLevel.Id = id
        managementLevel.LevelName = levelName
        Return managementLevel
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LevelName() As Global.System.String
        Get
            Return _LevelName
        End Get
        Set
            OnLevelNameChanging(value)
            ReportPropertyChanging("LevelName")
            _LevelName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LevelName")
            OnLevelNameChanged()
        End Set
    End Property

    Private _LevelName As Global.System.String
    Private Partial Sub OnLevelNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLevelNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "FK_Occupation_ManagementLevel", "Occupation")>
     Public Property Occupations() As EntityCollection(Of Occupation)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Occupation)("HRDModel.FK_Occupation_ManagementLevel", "Occupation")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Occupation)("HRDModel.FK_Occupation_ManagementLevel", "Occupation", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HRDModel", Name:="Master_Personal")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Master_Personal
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Master_Personal object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="employeeID">Initial value of the EmployeeID property.</param>
    ''' <param name="fullName">Initial value of the FullName property.</param>
    ''' <param name="gender">Initial value of the Gender property.</param>
    ''' <param name="religion">Initial value of the Religion property.</param>
    ''' <param name="occupationID">Initial value of the OccupationID property.</param>
    ''' <param name="officeId">Initial value of the OfficeId property.</param>
    ''' <param name="workerStatus">Initial value of the WorkerStatus property.</param>
    Public Shared Function CreateMaster_Personal(id As Global.System.Int32, employeeID As Global.System.String, fullName As Global.System.String, gender As Global.System.String, religion As Global.System.String, occupationID As Global.System.Int32, officeId As Global.System.Int32, workerStatus As Global.System.String) As Master_Personal
        Dim master_Personal as Master_Personal = New Master_Personal
        master_Personal.ID = id
        master_Personal.EmployeeID = employeeID
        master_Personal.FullName = fullName
        master_Personal.Gender = gender
        master_Personal.Religion = religion
        master_Personal.OccupationID = occupationID
        master_Personal.OfficeId = officeId
        master_Personal.WorkerStatus = workerStatus
        Return master_Personal
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EmployeeID() As Global.System.String
        Get
            Return _EmployeeID
        End Get
        Set
            OnEmployeeIDChanging(value)
            ReportPropertyChanging("EmployeeID")
            _EmployeeID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("EmployeeID")
            OnEmployeeIDChanged()
        End Set
    End Property

    Private _EmployeeID As Global.System.String
    Private Partial Sub OnEmployeeIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmployeeIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FullName() As Global.System.String
        Get
            Return _FullName
        End Get
        Set
            OnFullNameChanging(value)
            ReportPropertyChanging("FullName")
            _FullName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FullName")
            OnFullNameChanged()
        End Set
    End Property

    Private _FullName As Global.System.String
    Private Partial Sub OnFullNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFullNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property [Alias]() As Global.System.String
        Get
            Return _Alias
        End Get
        Set
            OnAliasChanging(value)
            ReportPropertyChanging("Alias")
            _Alias = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Alias")
            OnAliasChanged()
        End Set
    End Property

    Private _Alias As Global.System.String
    Private Partial Sub OnAliasChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAliasChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NIK() As Global.System.String
        Get
            Return _NIK
        End Get
        Set
            OnNIKChanging(value)
            ReportPropertyChanging("NIK")
            _NIK = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NIK")
            OnNIKChanged()
        End Set
    End Property

    Private _NIK As Global.System.String
    Private Partial Sub OnNIKChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNIKChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title_Front() As Global.System.String
        Get
            Return _Title_Front
        End Get
        Set
            OnTitle_FrontChanging(value)
            ReportPropertyChanging("Title_Front")
            _Title_Front = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title_Front")
            OnTitle_FrontChanged()
        End Set
    End Property

    Private _Title_Front As Global.System.String
    Private Partial Sub OnTitle_FrontChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitle_FrontChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title_Back() As Global.System.String
        Get
            Return _Title_Back
        End Get
        Set
            OnTitle_BackChanging(value)
            ReportPropertyChanging("Title_Back")
            _Title_Back = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title_Back")
            OnTitle_BackChanged()
        End Set
    End Property

    Private _Title_Back As Global.System.String
    Private Partial Sub OnTitle_BackChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitle_BackChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Gender() As Global.System.String
        Get
            Return _Gender
        End Get
        Set
            OnGenderChanging(value)
            ReportPropertyChanging("Gender")
            _Gender = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Gender")
            OnGenderChanged()
        End Set
    End Property

    Private _Gender As Global.System.String
    Private Partial Sub OnGenderChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGenderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PlaceOfBirth() As Global.System.String
        Get
            Return _PlaceOfBirth
        End Get
        Set
            OnPlaceOfBirthChanging(value)
            ReportPropertyChanging("PlaceOfBirth")
            _PlaceOfBirth = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PlaceOfBirth")
            OnPlaceOfBirthChanged()
        End Set
    End Property

    Private _PlaceOfBirth As Global.System.String
    Private Partial Sub OnPlaceOfBirthChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPlaceOfBirthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateOfBirth() As Nullable(Of Global.System.DateTime)
        Get
            Return _DateOfBirth
        End Get
        Set
            OnDateOfBirthChanging(value)
            ReportPropertyChanging("DateOfBirth")
            _DateOfBirth = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateOfBirth")
            OnDateOfBirthChanged()
        End Set
    End Property

    Private _DateOfBirth As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDateOfBirthChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDateOfBirthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Religion() As Global.System.String
        Get
            Return _Religion
        End Get
        Set
            OnReligionChanging(value)
            ReportPropertyChanging("Religion")
            _Religion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Religion")
            OnReligionChanged()
        End Set
    End Property

    Private _Religion As Global.System.String
    Private Partial Sub OnReligionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReligionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_Street() As Global.System.String
        Get
            Return _HomeAddress_Street
        End Get
        Set
            OnHomeAddress_StreetChanging(value)
            ReportPropertyChanging("HomeAddress_Street")
            _HomeAddress_Street = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_Street")
            OnHomeAddress_StreetChanged()
        End Set
    End Property

    Private _HomeAddress_Street As Global.System.String
    Private Partial Sub OnHomeAddress_StreetChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_StreetChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_City() As Global.System.String
        Get
            Return _HomeAddress_City
        End Get
        Set
            OnHomeAddress_CityChanging(value)
            ReportPropertyChanging("HomeAddress_City")
            _HomeAddress_City = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_City")
            OnHomeAddress_CityChanged()
        End Set
    End Property

    Private _HomeAddress_City As Global.System.String
    Private Partial Sub OnHomeAddress_CityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_CityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_PostCode() As Global.System.String
        Get
            Return _HomeAddress_PostCode
        End Get
        Set
            OnHomeAddress_PostCodeChanging(value)
            ReportPropertyChanging("HomeAddress_PostCode")
            _HomeAddress_PostCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_PostCode")
            OnHomeAddress_PostCodeChanged()
        End Set
    End Property

    Private _HomeAddress_PostCode As Global.System.String
    Private Partial Sub OnHomeAddress_PostCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_PostCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomePhone() As Global.System.String
        Get
            Return _HomePhone
        End Get
        Set
            OnHomePhoneChanging(value)
            ReportPropertyChanging("HomePhone")
            _HomePhone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomePhone")
            OnHomePhoneChanged()
        End Set
    End Property

    Private _HomePhone As Global.System.String
    Private Partial Sub OnHomePhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomePhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MobilePhone() As Global.System.String
        Get
            Return _MobilePhone
        End Get
        Set
            OnMobilePhoneChanging(value)
            ReportPropertyChanging("MobilePhone")
            _MobilePhone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MobilePhone")
            OnMobilePhoneChanged()
        End Set
    End Property

    Private _MobilePhone As Global.System.String
    Private Partial Sub OnMobilePhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMobilePhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MaritalStatus() As Global.System.String
        Get
            Return _MaritalStatus
        End Get
        Set
            OnMaritalStatusChanging(value)
            ReportPropertyChanging("MaritalStatus")
            _MaritalStatus = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MaritalStatus")
            OnMaritalStatusChanged()
        End Set
    End Property

    Private _MaritalStatus As Global.System.String
    Private Partial Sub OnMaritalStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMaritalStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Photo() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Photo)
        End Get
        Set
            OnPhotoChanging(value)
            ReportPropertyChanging("Photo")
            _Photo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Photo")
            OnPhotoChanged()
        End Set
    End Property

    Private _Photo As Global.System.Byte()
    Private Partial Sub OnPhotoChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPhotoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastUpdate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastUpdate
        End Get
        Set
            OnLastUpdateChanging(value)
            ReportPropertyChanging("LastUpdate")
            _LastUpdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastUpdate")
            OnLastUpdateChanged()
        End Set
    End Property

    Private _LastUpdate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastUpdateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastUpdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property WorkStartDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _WorkStartDate
        End Get
        Set
            OnWorkStartDateChanging(value)
            ReportPropertyChanging("WorkStartDate")
            _WorkStartDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("WorkStartDate")
            OnWorkStartDateChanged()
        End Set
    End Property

    Private _WorkStartDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnWorkStartDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnWorkStartDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BloodType() As Global.System.String
        Get
            Return _BloodType
        End Get
        Set
            OnBloodTypeChanging(value)
            ReportPropertyChanging("BloodType")
            _BloodType = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("BloodType")
            OnBloodTypeChanged()
        End Set
    End Property

    Private _BloodType As Global.System.String
    Private Partial Sub OnBloodTypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBloodTypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EmergencyCallNumber() As Global.System.String
        Get
            Return _EmergencyCallNumber
        End Get
        Set
            OnEmergencyCallNumberChanging(value)
            ReportPropertyChanging("EmergencyCallNumber")
            _EmergencyCallNumber = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("EmergencyCallNumber")
            OnEmergencyCallNumberChanged()
        End Set
    End Property

    Private _EmergencyCallNumber As Global.System.String
    Private Partial Sub OnEmergencyCallNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmergencyCallNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OccupationID() As Global.System.Int32
        Get
            Return _OccupationID
        End Get
        Set
            OnOccupationIDChanging(value)
            ReportPropertyChanging("OccupationID")
            _OccupationID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OccupationID")
            OnOccupationIDChanged()
        End Set
    End Property

    Private _OccupationID As Global.System.Int32
    Private Partial Sub OnOccupationIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOccupationIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OfficeId() As Global.System.Int32
        Get
            Return _OfficeId
        End Get
        Set
            OnOfficeIdChanging(value)
            ReportPropertyChanging("OfficeId")
            _OfficeId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OfficeId")
            OnOfficeIdChanged()
        End Set
    End Property

    Private _OfficeId As Global.System.Int32
    Private Partial Sub OnOfficeIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOfficeIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkerStatus() As Global.System.String
        Get
            Return _WorkerStatus
        End Get
        Set
            OnWorkerStatusChanging(value)
            ReportPropertyChanging("WorkerStatus")
            _WorkerStatus = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("WorkerStatus")
            OnWorkerStatusChanged()
        End Set
    End Property

    Private _WorkerStatus As Global.System.String
    Private Partial Sub OnWorkerStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWorkerStatusChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "FK_Master_Personal_Occupation", "Occupation")>
    Public Property Occupation() As Occupation
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Occupation)("HRDModel.FK_Master_Personal_Occupation", "Occupation").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Occupation)("HRDModel.FK_Master_Personal_Occupation", "Occupation").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OccupationReference() As EntityReference(Of Occupation)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Occupation)("HRDModel.FK_Master_Personal_Occupation", "Occupation")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Occupation)("HRDModel.FK_Master_Personal_Occupation", "Occupation", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "vOfficeMaster_Personal", "vOffice")>
    Public Property Office() As vOffice
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of vOffice)("HRDModel.vOfficeMaster_Personal", "vOffice").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of vOffice)("HRDModel.vOfficeMaster_Personal", "vOffice").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OfficeReference() As EntityReference(Of vOffice)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of vOffice)("HRDModel.vOfficeMaster_Personal", "vOffice")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of vOffice)("HRDModel.vOfficeMaster_Personal", "vOffice", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HRDModel", Name:="Occupation")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Occupation
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Occupation object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="managementLevelId">Initial value of the ManagementLevelId property.</param>
    ''' <param name="ordinat">Initial value of the Ordinat property.</param>
    ''' <param name="reportTo">Initial value of the ReportTo property.</param>
    Public Shared Function CreateOccupation(id As Global.System.Int32, name As Global.System.String, managementLevelId As Global.System.Int32, ordinat As Global.System.Int32, reportTo As Global.System.Int32) As Occupation
        Dim occupation as Occupation = New Occupation
        occupation.Id = id
        occupation.Name = name
        occupation.ManagementLevelId = managementLevelId
        occupation.Ordinat = ordinat
        occupation.ReportTo = reportTo
        Return occupation
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ManagementLevelId() As Global.System.Int32
        Get
            Return _ManagementLevelId
        End Get
        Set
            OnManagementLevelIdChanging(value)
            ReportPropertyChanging("ManagementLevelId")
            _ManagementLevelId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ManagementLevelId")
            OnManagementLevelIdChanged()
        End Set
    End Property

    Private _ManagementLevelId As Global.System.Int32
    Private Partial Sub OnManagementLevelIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnManagementLevelIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ordinat() As Global.System.Int32
        Get
            Return _Ordinat
        End Get
        Set
            OnOrdinatChanging(value)
            ReportPropertyChanging("Ordinat")
            _Ordinat = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Ordinat")
            OnOrdinatChanged()
        End Set
    End Property

    Private _Ordinat As Global.System.Int32
    Private Partial Sub OnOrdinatChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOrdinatChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ReportTo() As Global.System.Int32
        Get
            Return _ReportTo
        End Get
        Set
            OnReportToChanging(value)
            ReportPropertyChanging("ReportTo")
            _ReportTo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ReportTo")
            OnReportToChanged()
        End Set
    End Property

    Private _ReportTo As Global.System.Int32
    Private Partial Sub OnReportToChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnReportToChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "FK_Master_Personal_Occupation", "Master_Personal")>
     Public Property Master_Personal() As EntityCollection(Of Master_Personal)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Master_Personal)("HRDModel.FK_Master_Personal_Occupation", "Master_Personal")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Master_Personal)("HRDModel.FK_Master_Personal_Occupation", "Master_Personal", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "FK_Occupation_ManagementLevel", "ManagementLevel")>
    Public Property ManagementLevel() As ManagementLevel
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ManagementLevel)("HRDModel.FK_Occupation_ManagementLevel", "ManagementLevel").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ManagementLevel)("HRDModel.FK_Occupation_ManagementLevel", "ManagementLevel").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ManagementLevelReference() As EntityReference(Of ManagementLevel)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ManagementLevel)("HRDModel.FK_Occupation_ManagementLevel", "ManagementLevel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ManagementLevel)("HRDModel.FK_Occupation_ManagementLevel", "ManagementLevel", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HRDModel", Name:="vOffice")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class vOffice
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new vOffice object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="parent_ID">Initial value of the Parent_ID property.</param>
    ''' <param name="ordinal">Initial value of the Ordinal property.</param>
    Public Shared Function CreatevOffice(id As Global.System.Int32, name As Global.System.String, parent_ID As Global.System.Int32, ordinal As Global.System.Int32) As vOffice
        Dim vOffice as vOffice = New vOffice
        vOffice.Id = id
        vOffice.Name = name
        vOffice.Parent_ID = parent_ID
        vOffice.Ordinal = ordinal
        Return vOffice
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Code() As Global.System.String
        Get
            Return _Code
        End Get
        Set
            OnCodeChanging(value)
            ReportPropertyChanging("Code")
            _Code = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Code")
            OnCodeChanged()
        End Set
    End Property

    Private _Code As Global.System.String
    Private Partial Sub OnCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Abbreviation() As Global.System.String
        Get
            Return _Abbreviation
        End Get
        Set
            OnAbbreviationChanging(value)
            ReportPropertyChanging("Abbreviation")
            _Abbreviation = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Abbreviation")
            OnAbbreviationChanged()
        End Set
    End Property

    Private _Abbreviation As Global.System.String
    Private Partial Sub OnAbbreviationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAbbreviationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Parent_ID() As Global.System.Int32
        Get
            Return _Parent_ID
        End Get
        Set
            OnParent_IDChanging(value)
            ReportPropertyChanging("Parent_ID")
            _Parent_ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Parent_ID")
            OnParent_IDChanged()
        End Set
    End Property

    Private _Parent_ID As Global.System.Int32
    Private Partial Sub OnParent_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnParent_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ordinal() As Global.System.Int32
        Get
            Return _Ordinal
        End Get
        Set
            OnOrdinalChanging(value)
            ReportPropertyChanging("Ordinal")
            _Ordinal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Ordinal")
            OnOrdinalChanged()
        End Set
    End Property

    Private _Ordinal As Global.System.Int32
    Private Partial Sub OnOrdinalChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOrdinalChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("HRDModel", "vOfficeMaster_Personal", "Master_Personal")>
     Public Property Master_Personal() As EntityCollection(Of Master_Personal)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Master_Personal)("HRDModel.vOfficeMaster_Personal", "Master_Personal")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Master_Personal)("HRDModel.vOfficeMaster_Personal", "Master_Personal", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region

#Region "ComplexTypes"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmComplexTypeAttribute(NamespaceName:="HRDModel", Name:="ReportEmployee_Result")>
<DataContractAttribute(IsReference:=True)>
<Serializable()>
Public Partial Class ReportEmployee_Result
    Inherits ComplexObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ReportEmployee_Result object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="employeeID">Initial value of the EmployeeID property.</param>
    ''' <param name="fullName">Initial value of the FullName property.</param>
    ''' <param name="gender">Initial value of the Gender property.</param>
    ''' <param name="religion">Initial value of the Religion property.</param>
    ''' <param name="position">Initial value of the Position property.</param>
    ''' <param name="area">Initial value of the Area property.</param>
    ''' <param name="workerStatus">Initial value of the WorkerStatus property.</param>
    ''' <param name="levelName">Initial value of the LevelName property.</param>
    Public Shared Function CreateReportEmployee_Result(id As Global.System.Int32, employeeID As Global.System.String, fullName As Global.System.String, gender As Global.System.String, religion As Global.System.String, position As Global.System.String, area As Global.System.String, workerStatus As Global.System.String, levelName As Global.System.String) As ReportEmployee_Result
        Dim reportEmployee_Result as ReportEmployee_Result = New ReportEmployee_Result
        reportEmployee_Result.ID = id
        reportEmployee_Result.EmployeeID = employeeID
        reportEmployee_Result.FullName = fullName
        reportEmployee_Result.Gender = gender
        reportEmployee_Result.Religion = religion
        reportEmployee_Result.Position = position
        reportEmployee_Result.Area = area
        reportEmployee_Result.WorkerStatus = workerStatus
        reportEmployee_Result.LevelName = levelName
        Return reportEmployee_Result
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            OnIDChanging(value)
            ReportPropertyChanging("ID")
            _ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ID")
            OnIDChanged()
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EmployeeID() As Global.System.String
        Get
            Return _EmployeeID
        End Get
        Set
            OnEmployeeIDChanging(value)
            ReportPropertyChanging("EmployeeID")
            _EmployeeID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("EmployeeID")
            OnEmployeeIDChanged()
        End Set
    End Property

    Private _EmployeeID As Global.System.String
    Private Partial Sub OnEmployeeIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmployeeIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FullName() As Global.System.String
        Get
            Return _FullName
        End Get
        Set
            OnFullNameChanging(value)
            ReportPropertyChanging("FullName")
            _FullName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FullName")
            OnFullNameChanged()
        End Set
    End Property

    Private _FullName As Global.System.String
    Private Partial Sub OnFullNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFullNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property [Alias]() As Global.System.String
        Get
            Return _Alias
        End Get
        Set
            OnAliasChanging(value)
            ReportPropertyChanging("Alias")
            _Alias = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Alias")
            OnAliasChanged()
        End Set
    End Property

    Private _Alias As Global.System.String
    Private Partial Sub OnAliasChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAliasChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NIK() As Global.System.String
        Get
            Return _NIK
        End Get
        Set
            OnNIKChanging(value)
            ReportPropertyChanging("NIK")
            _NIK = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NIK")
            OnNIKChanged()
        End Set
    End Property

    Private _NIK As Global.System.String
    Private Partial Sub OnNIKChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNIKChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title_Front() As Global.System.String
        Get
            Return _Title_Front
        End Get
        Set
            OnTitle_FrontChanging(value)
            ReportPropertyChanging("Title_Front")
            _Title_Front = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title_Front")
            OnTitle_FrontChanged()
        End Set
    End Property

    Private _Title_Front As Global.System.String
    Private Partial Sub OnTitle_FrontChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitle_FrontChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title_Back() As Global.System.String
        Get
            Return _Title_Back
        End Get
        Set
            OnTitle_BackChanging(value)
            ReportPropertyChanging("Title_Back")
            _Title_Back = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title_Back")
            OnTitle_BackChanged()
        End Set
    End Property

    Private _Title_Back As Global.System.String
    Private Partial Sub OnTitle_BackChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitle_BackChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Gender() As Global.System.String
        Get
            Return _Gender
        End Get
        Set
            OnGenderChanging(value)
            ReportPropertyChanging("Gender")
            _Gender = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Gender")
            OnGenderChanged()
        End Set
    End Property

    Private _Gender As Global.System.String
    Private Partial Sub OnGenderChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGenderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PlaceOfBirth() As Global.System.String
        Get
            Return _PlaceOfBirth
        End Get
        Set
            OnPlaceOfBirthChanging(value)
            ReportPropertyChanging("PlaceOfBirth")
            _PlaceOfBirth = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PlaceOfBirth")
            OnPlaceOfBirthChanged()
        End Set
    End Property

    Private _PlaceOfBirth As Global.System.String
    Private Partial Sub OnPlaceOfBirthChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPlaceOfBirthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateOfBirth() As Nullable(Of Global.System.DateTime)
        Get
            Return _DateOfBirth
        End Get
        Set
            OnDateOfBirthChanging(value)
            ReportPropertyChanging("DateOfBirth")
            _DateOfBirth = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateOfBirth")
            OnDateOfBirthChanged()
        End Set
    End Property

    Private _DateOfBirth As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDateOfBirthChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDateOfBirthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Religion() As Global.System.String
        Get
            Return _Religion
        End Get
        Set
            OnReligionChanging(value)
            ReportPropertyChanging("Religion")
            _Religion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Religion")
            OnReligionChanged()
        End Set
    End Property

    Private _Religion As Global.System.String
    Private Partial Sub OnReligionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReligionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_Street() As Global.System.String
        Get
            Return _HomeAddress_Street
        End Get
        Set
            OnHomeAddress_StreetChanging(value)
            ReportPropertyChanging("HomeAddress_Street")
            _HomeAddress_Street = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_Street")
            OnHomeAddress_StreetChanged()
        End Set
    End Property

    Private _HomeAddress_Street As Global.System.String
    Private Partial Sub OnHomeAddress_StreetChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_StreetChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_City() As Global.System.String
        Get
            Return _HomeAddress_City
        End Get
        Set
            OnHomeAddress_CityChanging(value)
            ReportPropertyChanging("HomeAddress_City")
            _HomeAddress_City = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_City")
            OnHomeAddress_CityChanged()
        End Set
    End Property

    Private _HomeAddress_City As Global.System.String
    Private Partial Sub OnHomeAddress_CityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_CityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomeAddress_PostCode() As Global.System.String
        Get
            Return _HomeAddress_PostCode
        End Get
        Set
            OnHomeAddress_PostCodeChanging(value)
            ReportPropertyChanging("HomeAddress_PostCode")
            _HomeAddress_PostCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomeAddress_PostCode")
            OnHomeAddress_PostCodeChanged()
        End Set
    End Property

    Private _HomeAddress_PostCode As Global.System.String
    Private Partial Sub OnHomeAddress_PostCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomeAddress_PostCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HomePhone() As Global.System.String
        Get
            Return _HomePhone
        End Get
        Set
            OnHomePhoneChanging(value)
            ReportPropertyChanging("HomePhone")
            _HomePhone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("HomePhone")
            OnHomePhoneChanged()
        End Set
    End Property

    Private _HomePhone As Global.System.String
    Private Partial Sub OnHomePhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHomePhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MobilePhone() As Global.System.String
        Get
            Return _MobilePhone
        End Get
        Set
            OnMobilePhoneChanging(value)
            ReportPropertyChanging("MobilePhone")
            _MobilePhone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MobilePhone")
            OnMobilePhoneChanged()
        End Set
    End Property

    Private _MobilePhone As Global.System.String
    Private Partial Sub OnMobilePhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMobilePhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MaritalStatus() As Global.System.String
        Get
            Return _MaritalStatus
        End Get
        Set
            OnMaritalStatusChanging(value)
            ReportPropertyChanging("MaritalStatus")
            _MaritalStatus = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MaritalStatus")
            OnMaritalStatusChanged()
        End Set
    End Property

    Private _MaritalStatus As Global.System.String
    Private Partial Sub OnMaritalStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMaritalStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Photo() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Photo)
        End Get
        Set
            OnPhotoChanging(value)
            ReportPropertyChanging("Photo")
            _Photo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Photo")
            OnPhotoChanged()
        End Set
    End Property

    Private _Photo As Global.System.Byte()
    Private Partial Sub OnPhotoChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPhotoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastUpdate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastUpdate
        End Get
        Set
            OnLastUpdateChanging(value)
            ReportPropertyChanging("LastUpdate")
            _LastUpdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastUpdate")
            OnLastUpdateChanged()
        End Set
    End Property

    Private _LastUpdate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastUpdateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastUpdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property WorkStartDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _WorkStartDate
        End Get
        Set
            OnWorkStartDateChanging(value)
            ReportPropertyChanging("WorkStartDate")
            _WorkStartDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("WorkStartDate")
            OnWorkStartDateChanged()
        End Set
    End Property

    Private _WorkStartDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnWorkStartDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnWorkStartDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BloodType() As Global.System.String
        Get
            Return _BloodType
        End Get
        Set
            OnBloodTypeChanging(value)
            ReportPropertyChanging("BloodType")
            _BloodType = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("BloodType")
            OnBloodTypeChanged()
        End Set
    End Property

    Private _BloodType As Global.System.String
    Private Partial Sub OnBloodTypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBloodTypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EmergencyCallNumber() As Global.System.String
        Get
            Return _EmergencyCallNumber
        End Get
        Set
            OnEmergencyCallNumberChanging(value)
            ReportPropertyChanging("EmergencyCallNumber")
            _EmergencyCallNumber = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("EmergencyCallNumber")
            OnEmergencyCallNumberChanged()
        End Set
    End Property

    Private _EmergencyCallNumber As Global.System.String
    Private Partial Sub OnEmergencyCallNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmergencyCallNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Position() As Global.System.String
        Get
            Return _Position
        End Get
        Set
            OnPositionChanging(value)
            ReportPropertyChanging("Position")
            _Position = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Position")
            OnPositionChanged()
        End Set
    End Property

    Private _Position As Global.System.String
    Private Partial Sub OnPositionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPositionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Area() As Global.System.String
        Get
            Return _Area
        End Get
        Set
            OnAreaChanging(value)
            ReportPropertyChanging("Area")
            _Area = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Area")
            OnAreaChanged()
        End Set
    End Property

    Private _Area As Global.System.String
    Private Partial Sub OnAreaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAreaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkerStatus() As Global.System.String
        Get
            Return _WorkerStatus
        End Get
        Set
            OnWorkerStatusChanging(value)
            ReportPropertyChanging("WorkerStatus")
            _WorkerStatus = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("WorkerStatus")
            OnWorkerStatusChanged()
        End Set
    End Property

    Private _WorkerStatus As Global.System.String
    Private Partial Sub OnWorkerStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWorkerStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LevelName() As Global.System.String
        Get
            Return _LevelName
        End Get
        Set
            OnLevelNameChanging(value)
            ReportPropertyChanging("LevelName")
            _LevelName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LevelName")
            OnLevelNameChanged()
        End Set
    End Property

    Private _LevelName As Global.System.String
    Private Partial Sub OnLevelNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLevelNameChanged()
    End Sub

    #End Region

End Class

#End Region


