'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MDKAccessSync
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://halotec-indonesia.com/", ConfigurationName:="MDKAccessSync.MDKAccessSyncSoap")>  _
    Public Interface MDKAccessSyncSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/TestConnection", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TestConnection() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_MaxIDHistory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_MaxIDHistory() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/insert_History", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function insert_History(ByVal data As MDKAccessSync.tblMisc_History) As MDKAccessSync.StatusMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_MaxKodePeru", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function get_MaxKodePeru() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/insert_Perusahaan", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function insert_Perusahaan(ByVal data As MDKAccessSync.TblMst_Perusahaan) As MDKAccessSync.StatusMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_maxNoRec", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function get_maxNoRec() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/insert_NoRec", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function insert_NoRec(ByVal data As MDKAccessSync.TblMst_NoRec) As MDKAccessSync.StatusMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_KodeBarang", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function get_KodeBarang() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/insert_Barang", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function insert_Barang(ByVal data As MDKAccessSync.TblMst_Barang) As MDKAccessSync.StatusMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_NoPenimbangan2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function get_NoPenimbangan2() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/get_TglMasukPenimbangan2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function get_TglMasukPenimbangan2() As Date
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://halotec-indonesia.com/insert_Penimbangan2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(StructuralObject)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntityKeyMember()))>  _
        Function insert_Penimbangan2(ByVal data As MDKAccessSync.TblTrans_Penimbangan2) As MDKAccessSync.StatusMessage
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class tblMisc_History
        Inherits EntityObject
        
        Private historyIDField As Integer
        
        Private operatorField As String
        
        Private waktuField As System.Nullable(Of Date)
        
        Private norecordField As String
        
        Private jenisField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property historyID() As Integer
            Get
                Return Me.historyIDField
            End Get
            Set
                Me.historyIDField = value
                Me.RaisePropertyChanged("historyID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property [Operator]() As String
            Get
                Return Me.operatorField
            End Get
            Set
                Me.operatorField = value
                Me.RaisePropertyChanged("Operator")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property waktu() As System.Nullable(Of Date)
            Get
                Return Me.waktuField
            End Get
            Set
                Me.waktuField = value
                Me.RaisePropertyChanged("waktu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property norecord() As String
            Get
                Return Me.norecordField
            End Get
            Set
                Me.norecordField = value
                Me.RaisePropertyChanged("norecord")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property jenis() As String
            Get
                Return Me.jenisField
            End Get
            Set
                Me.jenisField = value
                Me.RaisePropertyChanged("jenis")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(TblTrans_Penimbangan2)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_Barang)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_NoRec)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_Perusahaan)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(tblMisc_History)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public MustInherit Class EntityObject
        Inherits StructuralObject
        
        Private entityKeyField As EntityKey
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property EntityKey() As EntityKey
            Get
                Return Me.entityKeyField
            End Get
            Set
                Me.entityKeyField = value
                Me.RaisePropertyChanged("EntityKey")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class EntityKey
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private entitySetNameField As String
        
        Private entityContainerNameField As String
        
        Private entityKeyValuesField() As EntityKeyMember
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property EntitySetName() As String
            Get
                Return Me.entitySetNameField
            End Get
            Set
                Me.entitySetNameField = value
                Me.RaisePropertyChanged("EntitySetName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property EntityContainerName() As String
            Get
                Return Me.entityContainerNameField
            End Get
            Set
                Me.entityContainerNameField = value
                Me.RaisePropertyChanged("EntityContainerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=2)>  _
        Public Property EntityKeyValues() As EntityKeyMember()
            Get
                Return Me.entityKeyValuesField
            End Get
            Set
                Me.entityKeyValuesField = value
                Me.RaisePropertyChanged("EntityKeyValues")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class EntityKeyMember
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private keyField As String
        
        Private valueField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
                Me.RaisePropertyChanged("Key")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class StatusMessage
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As Boolean
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("Message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityObject)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblTrans_Penimbangan2)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_Barang)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_NoRec)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TblMst_Perusahaan)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(tblMisc_History)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public MustInherit Class StructuralObject
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class TblTrans_Penimbangan2
        Inherits EntityObject
        
        Private noRecordField As String
        
        Private tglMasukField As System.Nullable(Of Date)
        
        Private tglKeluarField As System.Nullable(Of Date)
        
        Private noPolisiField As String
        
        Private sopirField As String
        
        Private kodePeruField As System.Nullable(Of Integer)
        
        Private kodeBrgField As System.Nullable(Of Integer)
        
        Private berat1Field As System.Nullable(Of Integer)
        
        Private berat2Field As System.Nullable(Of Integer)
        
        Private deliveryNoteField As String
        
        Private clerk1Field As String
        
        Private clerk2Field As String
        
        Private copyField As System.Nullable(Of Integer)
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NoRecord() As String
            Get
                Return Me.noRecordField
            End Get
            Set
                Me.noRecordField = value
                Me.RaisePropertyChanged("NoRecord")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property TglMasuk() As System.Nullable(Of Date)
            Get
                Return Me.tglMasukField
            End Get
            Set
                Me.tglMasukField = value
                Me.RaisePropertyChanged("TglMasuk")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property TglKeluar() As System.Nullable(Of Date)
            Get
                Return Me.tglKeluarField
            End Get
            Set
                Me.tglKeluarField = value
                Me.RaisePropertyChanged("TglKeluar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NoPolisi() As String
            Get
                Return Me.noPolisiField
            End Get
            Set
                Me.noPolisiField = value
                Me.RaisePropertyChanged("NoPolisi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Sopir() As String
            Get
                Return Me.sopirField
            End Get
            Set
                Me.sopirField = value
                Me.RaisePropertyChanged("Sopir")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property KodePeru() As System.Nullable(Of Integer)
            Get
                Return Me.kodePeruField
            End Get
            Set
                Me.kodePeruField = value
                Me.RaisePropertyChanged("KodePeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property KodeBrg() As System.Nullable(Of Integer)
            Get
                Return Me.kodeBrgField
            End Get
            Set
                Me.kodeBrgField = value
                Me.RaisePropertyChanged("KodeBrg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property Berat1() As System.Nullable(Of Integer)
            Get
                Return Me.berat1Field
            End Get
            Set
                Me.berat1Field = value
                Me.RaisePropertyChanged("Berat1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property Berat2() As System.Nullable(Of Integer)
            Get
                Return Me.berat2Field
            End Get
            Set
                Me.berat2Field = value
                Me.RaisePropertyChanged("Berat2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property DeliveryNote() As String
            Get
                Return Me.deliveryNoteField
            End Get
            Set
                Me.deliveryNoteField = value
                Me.RaisePropertyChanged("DeliveryNote")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Clerk1() As String
            Get
                Return Me.clerk1Field
            End Get
            Set
                Me.clerk1Field = value
                Me.RaisePropertyChanged("Clerk1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Clerk2() As String
            Get
                Return Me.clerk2Field
            End Get
            Set
                Me.clerk2Field = value
                Me.RaisePropertyChanged("Clerk2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=12)>  _
        Public Property Copy() As System.Nullable(Of Integer)
            Get
                Return Me.copyField
            End Get
            Set
                Me.copyField = value
                Me.RaisePropertyChanged("Copy")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class TblMst_Barang
        Inherits EntityObject
        
        Private kodeBrgField As Integer
        
        Private noBrgField As String
        
        Private namaBrgField As String
        
        Private keteranganField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property KodeBrg() As Integer
            Get
                Return Me.kodeBrgField
            End Get
            Set
                Me.kodeBrgField = value
                Me.RaisePropertyChanged("KodeBrg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NoBrg() As String
            Get
                Return Me.noBrgField
            End Get
            Set
                Me.noBrgField = value
                Me.RaisePropertyChanged("NoBrg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NamaBrg() As String
            Get
                Return Me.namaBrgField
            End Get
            Set
                Me.namaBrgField = value
                Me.RaisePropertyChanged("NamaBrg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Keterangan() As String
            Get
                Return Me.keteranganField
            End Get
            Set
                Me.keteranganField = value
                Me.RaisePropertyChanged("Keterangan")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class TblMst_NoRec
        Inherits EntityObject
        
        Private noRecordField As String
        
        Private noUrutField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NoRecord() As String
            Get
                Return Me.noRecordField
            End Get
            Set
                Me.noRecordField = value
                Me.RaisePropertyChanged("NoRecord")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NoUrut() As Integer
            Get
                Return Me.noUrutField
            End Get
            Set
                Me.noUrutField = value
                Me.RaisePropertyChanged("NoUrut")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://halotec-indonesia.com/")>  _
    Partial Public Class TblMst_Perusahaan
        Inherits EntityObject
        
        Private kodePeruField As Integer
        
        Private noPeruField As String
        
        Private namaPeruField As String
        
        Private alamatPeru1Field As String
        
        Private alamatPeru2Field As String
        
        Private kotaPeruField As String
        
        Private telpPeruField As String
        
        Private faxPeruField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property KodePeru() As Integer
            Get
                Return Me.kodePeruField
            End Get
            Set
                Me.kodePeruField = value
                Me.RaisePropertyChanged("KodePeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NoPeru() As String
            Get
                Return Me.noPeruField
            End Get
            Set
                Me.noPeruField = value
                Me.RaisePropertyChanged("NoPeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NamaPeru() As String
            Get
                Return Me.namaPeruField
            End Get
            Set
                Me.namaPeruField = value
                Me.RaisePropertyChanged("NamaPeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property AlamatPeru1() As String
            Get
                Return Me.alamatPeru1Field
            End Get
            Set
                Me.alamatPeru1Field = value
                Me.RaisePropertyChanged("AlamatPeru1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property AlamatPeru2() As String
            Get
                Return Me.alamatPeru2Field
            End Get
            Set
                Me.alamatPeru2Field = value
                Me.RaisePropertyChanged("AlamatPeru2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property KotaPeru() As String
            Get
                Return Me.kotaPeruField
            End Get
            Set
                Me.kotaPeruField = value
                Me.RaisePropertyChanged("KotaPeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property TelpPeru() As String
            Get
                Return Me.telpPeruField
            End Get
            Set
                Me.telpPeruField = value
                Me.RaisePropertyChanged("TelpPeru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property FaxPeru() As String
            Get
                Return Me.faxPeruField
            End Get
            Set
                Me.faxPeruField = value
                Me.RaisePropertyChanged("FaxPeru")
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MDKAccessSyncSoapChannel
        Inherits MDKAccessSync.MDKAccessSyncSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MDKAccessSyncSoapClient
        Inherits System.ServiceModel.ClientBase(Of MDKAccessSync.MDKAccessSyncSoap)
        Implements MDKAccessSync.MDKAccessSyncSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TestConnection() As String Implements MDKAccessSync.MDKAccessSyncSoap.TestConnection
            Return MyBase.Channel.TestConnection
        End Function
        
        Public Function get_MaxIDHistory() As Integer Implements MDKAccessSync.MDKAccessSyncSoap.get_MaxIDHistory
            Return MyBase.Channel.get_MaxIDHistory
        End Function
        
        Public Function insert_History(ByVal data As MDKAccessSync.tblMisc_History) As MDKAccessSync.StatusMessage Implements MDKAccessSync.MDKAccessSyncSoap.insert_History
            Return MyBase.Channel.insert_History(data)
        End Function
        
        Public Function get_MaxKodePeru() As Integer Implements MDKAccessSync.MDKAccessSyncSoap.get_MaxKodePeru
            Return MyBase.Channel.get_MaxKodePeru
        End Function
        
        Public Function insert_Perusahaan(ByVal data As MDKAccessSync.TblMst_Perusahaan) As MDKAccessSync.StatusMessage Implements MDKAccessSync.MDKAccessSyncSoap.insert_Perusahaan
            Return MyBase.Channel.insert_Perusahaan(data)
        End Function
        
        Public Function get_maxNoRec() As Integer Implements MDKAccessSync.MDKAccessSyncSoap.get_maxNoRec
            Return MyBase.Channel.get_maxNoRec
        End Function
        
        Public Function insert_NoRec(ByVal data As MDKAccessSync.TblMst_NoRec) As MDKAccessSync.StatusMessage Implements MDKAccessSync.MDKAccessSyncSoap.insert_NoRec
            Return MyBase.Channel.insert_NoRec(data)
        End Function
        
        Public Function get_KodeBarang() As Integer Implements MDKAccessSync.MDKAccessSyncSoap.get_KodeBarang
            Return MyBase.Channel.get_KodeBarang
        End Function
        
        Public Function insert_Barang(ByVal data As MDKAccessSync.TblMst_Barang) As MDKAccessSync.StatusMessage Implements MDKAccessSync.MDKAccessSyncSoap.insert_Barang
            Return MyBase.Channel.insert_Barang(data)
        End Function
        
        Public Function get_NoPenimbangan2() As Integer Implements MDKAccessSync.MDKAccessSyncSoap.get_NoPenimbangan2
            Return MyBase.Channel.get_NoPenimbangan2
        End Function
        
        Public Function get_TglMasukPenimbangan2() As Date Implements MDKAccessSync.MDKAccessSyncSoap.get_TglMasukPenimbangan2
            Return MyBase.Channel.get_TglMasukPenimbangan2
        End Function
        
        Public Function insert_Penimbangan2(ByVal data As MDKAccessSync.TblTrans_Penimbangan2) As MDKAccessSync.StatusMessage Implements MDKAccessSync.MDKAccessSyncSoap.insert_Penimbangan2
            Return MyBase.Channel.insert_Penimbangan2(data)
        End Function
    End Class
End Namespace
